package quiz;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author fhmrz
 */
public class Quiz extends javax.swing.JFrame {

    private DatabaseConnector dbConnector;
    private Classroom selectedClassroom;
    private int kelasid;
    private Quiz selectedQuiz;
    private String kuisnama;
    private int quizid;
    
    public Quiz() {
        initComponents();
        dbConnector = new DatabaseConnector();
        loadClasses();
    }
    
    static class DatabaseConnector {
        private final String URL = "jdbc:mysql://localhost:3306/quizdb";
        private final String USERNAME = "root";
        private final String PASSWORD = "";

        public Connection getConnection() throws SQLException {
            return DriverManager.getConnection(URL, USERNAME, PASSWORD);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel1.setText("Kelas");

        jLabel2.setText("Kuis");

        jButton1.setText("Pilih");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PILIH KUIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                openEditSoalDosen(selectedClassroom.getKelasid(), selectedQuiz.getQuizId());
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed


    private void loadClasses() {
        try {
            Connection connection = dbConnector.getConnection();
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM kelas");

            List<Classroom> classrooms = new ArrayList<>();
            while (resultSet.next()) {
                kelasid = resultSet.getInt("kelasid");
                String className = resultSet.getString("namakelas");
                classrooms.add(new Classroom(kelasid, className));
            }

            DefaultListModel<String> classListModel = new DefaultListModel<>();
            for (Classroom classroom : classrooms) {
                classListModel.addElement(classroom.getKelasnama());
            }
            jList1.setModel(classListModel);

            resultSet.close();
            statement.close();
            connection.close();

            jList1.addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    selectedClassroom = classrooms.get(jList1.getSelectedIndex());
                    loadQuizzes();
                }
            });
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void loadQuizzes() {
        try {
            Connection connection = dbConnector.getConnection();
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM kuis WHERE kelasid = " + selectedClassroom.getKelasid();
            ResultSet resultSet = statement.executeQuery(query);

            List<Quiz> quizzes = new ArrayList<>();
            while (resultSet.next()) {
                quizid = resultSet.getInt("kuisid");
                String kuisnama = resultSet.getString("namakuis");
                quizzes.add(new Quiz(quizid, kuisnama));
            }

            DefaultListModel<String> quizListModel = new DefaultListModel<>();
            for (Quiz quiz : quizzes) {
                quizListModel.addElement(quiz.getKuisNama());
            }
            jList2.setModel(quizListModel);

            resultSet.close();
            statement.close();
            connection.close();

            jList2.addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    selectedQuiz = quizzes.get(jList2.getSelectedIndex());
                }
            });
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void openEditSoalDosen(int kelasid, int quizid) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Quiz.this.dispose();
                new EditSoalDosen(kelasid, quizid).setVisible(true);
            }
        });
    }


     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    public Quiz(int quizid, String kuisnama) {
            this.quizid = quizid;
            this.kuisnama = kuisnama;
        }
    
        public int getQuizId() {
            return quizid;
        }

        public String getKuisNama() {
            return kuisnama;
         }
        
    }

    // Kelas untuk merepresentasikan kelas
    class Classroom {
        int kelasid;
        String kelasnama;

    public Classroom(int kelasid, String kelasnama) {
        this.kelasid = kelasid;
        this.kelasnama = kelasnama;
    }

    public int getKelasid() {
        return kelasid;
    }

    public String getKelasnama() {
        return kelasnama;
    }
}
